server {
    listen 80;
    server_name wolfmother613.web.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name wolfmother613.web.id;

    ssl_certificate /etc/nginx/ssl/server.pem;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # Auth Service (Handles /auth/login, /auth/refresh, etc)
    location /auth {
        proxy_pass http://sso:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Service & Main App (Handles /api/v1/..., /public/..., etc)
    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
